const { default: makeWASocket, 
  useMultiFileAuthState, DisconnectReason, 
  fetchLatestBaileysVersion
} = require('@whiskeysockets/baileys');

const P = require('pino');
const qrcode = require('qrcode-terminal');

async function startBot() {
  const { state, saveCreds } = await useMultiFileAuthState('auth_info_baileys');

  const { version, isLatest } = await fetchLatestBaileysVersion();
  console.log(`Using Baileys Version: ${version}, isLatest: ${isLatest}`);

  const sock = makeWASocket({
    version,
    logger: P({ level: 'silent' }),
    auth: state
  });

  sock.ev.on('creds.update', saveCreds);

  sock.ev.on('connection.update', (update) => {
    const { connection, lastDisconnect, qr } = update;

    if (qr) {
      console.log('📌 Scan QR ini dengan WhatsApp:');
      qrcode.generate(qr, { small: true });
    }

    if (connection === 'close') {
      const shouldReconnect = lastDisconnect?.error?.output?.statusCode !== DisconnectReason.loggedOut;
      console.log('Connection closed, reconnecting:', shouldReconnect);
      if (shouldReconnect) {
        startBot();
      }
    } else if (connection === 'open') {
      console.log('✅ Bot is connected & ready!');
    }
  });

  sock.ev.on('messages.upsert', async ({ messages }) => {
    const msg = messages[0];
    if (!msg.message) return;

    const from = msg.key.remoteJid;
    const text = msg.message.conversation || msg.message.extendedTextMessage?.text;

    console.log(`📥 Pesan masuk dari ${from}: ${text}`);

    const { kirimSpam } = require('./spam.js');
    if (text.toLowerCase() === 'gas spam') {
    await kirimSpam(sock, from);
   }

    const replies = {
      '.s': 'mohon maaf bot nya tidak ada fitur membuat sticker',
      'rusia': 'Rusia adalah negara terluas di dunia yang membentang dari Eropa Timur hingga Asia Utara dengan luas wilayah lebih dari 17 juta km persegi. Ibukotanya adalah Moskow, yang juga menjadi pusat pemerintahan, budaya, dan ekonomi. Rusia dikenal dengan sejarah kekaisaran, Revolusi Bolshevik, serta era Uni Soviet yang pernah menjadi salah satu negara adidaya. Negara ini memiliki kekayaan alam melimpah seperti minyak, gas alam, dan mineral. Selain itu, Rusia memiliki keindahan arsitektur khas seperti Kremlin, Katedral St. Basil, dan Trans-Siberian Railway yang terkenal sebagai jalur kereta terpanjang di dunia.',
      'india': 'India adalah negara di Asia Selatan dengan populasi terbesar kedua di dunia setelah China, dengan lebih dari 1,4 miliar jiwa. Ibukotanya adalah New Delhi, sedangkan kota terbesarnya adalah Mumbai. India dikenal sebagai negara dengan keanekaragaman budaya, agama, bahasa, dan tradisi yang sangat kaya. Negara ini merupakan tempat lahirnya agama Hindu, Buddha, Jainisme, dan Sikhisme. India juga terkenal dengan industri film Bollywood yang mendunia. Di bidang teknologi, India menjadi salah satu pusat pengembangan IT terbesar dengan banyak tenaga profesional yang bekerja di bidang teknologi global.',
      'jerman': 'Jerman adalah negara di Eropa Tengah yang memiliki peran penting dalam sejarah Eropa dan dunia, terutama pada abad ke-20. Ibukotanya adalah Berlin, yang juga dikenal sebagai pusat budaya dan seni. Jerman memiliki perekonomian terbesar di Eropa dan salah satu yang terkuat di dunia, terkenal dengan industri otomotifnya seperti Mercedes-Benz, BMW, dan Volkswagen. Negara ini juga memiliki sistem pendidikan tinggi yang diakui dunia, dengan banyak universitas bergengsi. Jerman memiliki warisan budaya yang kaya mulai dari musik klasik hingga arsitektur kastil kuno dan kota-kota bersejarah.',
      'italia': 'Italia adalah negara di Eropa Selatan yang terkenal dengan warisan budaya, sejarah Romawi, dan seni Renaisans. Ibukotanya adalah Roma, kota bersejarah yang menjadi pusat Kekaisaran Romawi dan rumah bagi Vatikan, pusat agama Katolik. Italia terkenal dengan keindahan kota-kotanya seperti Venesia, Florence, dan Milan. Negara ini juga diakui sebagai kiblat mode dunia dan terkenal dengan kuliner khas seperti pasta, pizza, dan gelato. Selain itu, Italia memiliki industri otomotif terkenal seperti Ferrari, Lamborghini, dan Ducati.',
      'vietnam': 'Vietnam adalah negara di Asia Tenggara yang terkenal dengan sejarah panjangnya, termasuk Perang Vietnam. Ibukotanya adalah Hanoi, sedangkan kota terbesar sekaligus pusat ekonomi adalah Ho Chi Minh City (dulu Saigon). Vietnam dikenal dengan lanskap alam yang indah seperti Teluk Ha Long, sawah terasering Sapa, dan Delta Mekong. Negara ini juga terkenal dengan kuliner khasnya seperti pho, banh mi, dan kopi Vietnam. Ekonomi Vietnam berkembang pesat dalam beberapa dekade terakhir dengan sektor manufaktur dan ekspor yang kuat.',
      'israel': 'semoga Allah memerdekakan palestina dan menghancurkan negara israel (BABI) dari muka bumi, sungguh terkutuk bangsa zionis laknatullah',
      'perang dunia pertama': 'Perang Dunia Pertama (1914–1918) adalah perang global besar pertama dalam sejarah modern, melibatkan sekitar 70 juta personel militer dari berbagai benua. Perang ini dipicu oleh pembunuhan Archduke Franz Ferdinand dari Austria-Hongaria di Sarajevo pada 28 Juni 1914, yang memicu Austria-Hongaria menyatakan perang pada Serbia. Sistem aliansi yang kompleks membuat negara-negara besar ikut terlibat. Blok Sentral (Jerman, Austria-Hongaria, Kekaisaran Ottoman, Bulgaria) bertempur melawan Blok Sekutu (Britania Raya, Prancis, Kekaisaran Rusia, kemudian Italia pada 1915, Amerika Serikat pada 1917, dan beberapa negara lainnya). Tahun 1914: Jerman menyerbu Belgia dan Prancis, memicu Front Barat dengan parit panjang yang buntu. Di Front Timur, Rusia melawan Jerman dan Austria-Hongaria. 1915: Italia bergabung dengan Sekutu, Gallipoli Campaign diluncurkan melawan Ottoman, tetapi gagal. 1916: Pertempuran Verdun dan Somme menjadi simbol horor perang parit, menewaskan jutaan tentara. 1917: Revolusi Rusia menjatuhkan Tsar, membawa Bolshevik berkuasa; Rusia keluar dari perang lewat Perjanjian Brest-Litovsk (1918). Amerika Serikat masuk perang karena serangan kapal selam Jerman tanpa batas (misalnya tenggelamnya Lusitania 1915) dan Telegram Zimmermann. 1918: Jerman meluncurkan Serangan Musim Semi, nyaris menang di Front Barat, tetapi gagal total setelah Sekutu mendapat bala bantuan Amerika. Kekaisaran Ottoman dan Austria-Hongaria kolaps; Jerman dipaksa menandatangani gencatan senjata pada 11 November 1918 di Compiègne. Perang berakhir dengan Perjanjian Versailles (1919) yang menghukum Jerman sangat berat, merubah peta Eropa (lahir Polandia, Cekoslowakia, Yugoslavia), memicu kebangkitan nasionalisme ekstrem di Jerman. Korban tewas diperkirakan 9-16 juta tentara, 7 juta warga sipil. Teknologi modern seperti tank, senapan mesin, gas beracun, pesawat tempur, kapal selam menjadi tonggak baru peperangan. Perang Dunia Pertama menandai runtuhnya 4 kekaisaran besar: Jerman, Rusia, Austria-Hongaria, dan Ottoman, membuka jalan pada Perang Dunia Kedua yang dipicu ketegangan lanjutan di Eropa. Dampaknya terasa dalam politik global, perjanjian internasional, gerakan kemerdekaan di koloni, hingga pembentukan Liga Bangsa-Bangsa meski gagal mencegah perang lanjutan. Perang ini meninggalkan luka mendalam dan menjadi pelajaran penting betapa destruktifnya konflik total modern.',
      'bokep jilbab': 'https://bokepjilbob.click/',
      'french guiana': 'Guyana Prancis adalah wilayah seberang laut Prancis di pesisir timur laut Amerika Selatan, terkenal dengan hutan hujan lebat dan Pusat Antariksa Kourou. Ibukotanya adalah Cayenne.',
      'mulai': '.menu',
      'bahamas': 'Bahama adalah negara kepulauan di Samudra Atlantik yang terkenal dengan pantai tropis dan wisata kapal pesiar. Ibukotanya adalah Nassau.',
      'barbados': 'Barbados adalah negara pulau di Karibia Timur yang terkenal dengan pantai pasir putih dan budaya musik calypso. Ibukotanya adalah Bridgetown.',
      'saint lucia': 'Saint Lucia adalah negara pulau di Karibia dengan gunung kembar Pitons yang ikonik. Ibukotanya adalah Castries.',
      'saint vincent and the grenadines': 'Saint Vincent dan Grenadines adalah negara kepulauan di Karibia yang terkenal dengan pantai tropis dan pulau-pulau kecilnya. Ibukotanya adalah Kingstown.',
      'grenada': 'Grenada adalah negara pulau di Karibia yang dikenal sebagai "Pulau Rempah-rempah". Ibukotanya adalah St. George\'s.',
      'antigua and barbuda': 'Antigua dan Barbuda adalah negara kepulauan di Karibia yang terkenal dengan pantai berpasir putih dan resor wisata. Ibukotanya adalah St. John\'s.',
      'saint kitts and nevis': 'Saint Kitts dan Nevis adalah federasi dua pulau di Karibia yang terkenal dengan pantai dan pegunungan vulkanik. Ibukotanya adalah Basseterre.',
      'dominica': 'Dominika adalah negara pulau di Karibia dengan hutan hujan tropis, sungai, dan sumber air panas alami. Ibukotanya adalah Roseau.',
      'haiti': 'Haiti adalah negara di pulau Hispaniola di Karibia, berbagi pulau dengan Republik Dominika. Ibukotanya adalah Port-au-Prince.',
      'dominican republic': 'Republik Dominika adalah negara di Karibia Timur di pulau Hispaniola, terkenal dengan resor pantai dan pegunungan. Ibukotanya adalah Santo Domingo.',
      'jamaica': 'Jamaika adalah negara pulau di Karibia yang terkenal dengan musik reggae dan pantai tropisnya. Ibukotanya adalah Kingston.',
      'trinidad and tobago': 'Trinidad dan Tobago adalah negara kepulauan di lepas pantai timur Venezuela, terkenal dengan festival karnaval. Ibukotanya adalah Port of Spain.',
      'cuba': 'Kuba adalah negara pulau terbesar di Karibia, terkenal dengan Havana Tua dan sejarah revolusinya. Ibukotanya adalah Havana.',
      'mexico': 'Meksiko adalah negara di Amerika Utara dengan warisan Aztec dan Maya serta pantai tropis. Ibukotanya adalah Mexico City.',
      'guatemala': 'Guatemala adalah negara di Amerika Tengah yang terkenal dengan situs Maya kuno Tikal. Ibukotanya adalah Kota Guatemala.',
      'belize': 'Belize adalah negara di Amerika Tengah yang terkenal dengan terumbu karang Belize Barrier Reef. Ibukotanya adalah Belmopan.',
      'honduras': 'Honduras adalah negara di Amerika Tengah dengan pantai di Laut Karibia dan Pasifik. Ibukotanya adalah Tegucigalpa.',
      'el salvador': 'El Salvador adalah negara terkecil di Amerika Tengah, terkenal dengan pantai surfing. Ibukotanya adalah San Salvador.',
      'nicaragua': 'Nikaragua adalah negara di Amerika Tengah dengan danau besar dan gunung berapi aktif. Ibukotanya adalah Managua.',
      'costa rica': 'Kosta Rika adalah negara di Amerika Tengah terkenal dengan ekowisata, hutan hujan, dan keanekaragaman hayati. Ibukotanya adalah San José.',
      'panama': 'Panama adalah negara di Amerika Tengah yang terkenal dengan Terusan Panama penghubung Samudra Atlantik dan Pasifik. Ibukotanya adalah Panama City.',
      'bermuda': 'Bermuda adalah wilayah seberang laut Britania di Atlantik Utara, terkenal dengan pantai pasir merah muda. Ibukotanya adalah Hamilton.',
      'palestina': 'FREEEE PALESTIN, SEMOGA KAUM ZIONIS DIHANCURKAN DARI MUKA BUMI INI, AMINN YA ALLAH',
      'qatar': 'Qatar adalah negara kecil di Timur Tengah yang kaya akan gas alam dan minyak bumi. Ibukotanya adalah Doha, kota modern dengan gedung pencakar langit dan museum seni Islam. Qatar menjadi tuan rumah Piala Dunia FIFA 2022.',
      'ivory coast': 'Pantai Gading (Ivory Coast) adalah negara di Afrika Barat yang terkenal dengan produksi kakao terbesar di dunia. Ibukotanya adalah Yamoussoukro, sedangkan pusat komersialnya adalah Abidjan.',
      'mali': 'Mali adalah negara di Afrika Barat yang terkenal dengan kota Timbuktu, pusat pembelajaran Islam kuno. Ibukotanya adalah Bamako.',
      'senegal': 'Senegal adalah negara di Afrika Barat dengan ibukota Dakar, terkenal dengan Pulau Gorée dan budaya musiknya.',
      'cameroon': 'Kamerun adalah negara di Afrika Tengah dengan keanekaragaman etnis dan lanskap dari pantai ke pegunungan. Ibukotanya adalah Yaoundé.',
      'ethiopia': 'Ethiopia adalah negara di Tanduk Afrika, salah satu negara tertua di dunia, terkenal dengan Lalibela dan sejarah Kekaisaran Aksum. Ibukotanya adalah Addis Ababa.',
      'eritrea': 'Eritrea adalah negara di Tanduk Afrika yang terletak di Laut Merah. Ibukotanya adalah Asmara.',
      'djibouti': 'Djibouti adalah negara kecil di Tanduk Afrika, memiliki pelabuhan penting di Laut Merah. Ibukotanya adalah Djibouti City.',
      'somalia': 'Somalia adalah negara di Tanduk Afrika dengan garis pantai terpanjang di Afrika. Ibukotanya adalah Mogadishu.',
      'sudan selatan': 'Sudan Selatan adalah negara termuda di dunia yang merdeka pada 2011 dari Sudan. Ibukotanya adalah Juba.',
      'zimbabwe': 'Zimbabwe adalah negara di Afrika bagian selatan, terkenal dengan Air Terjun Victoria dan reruntuhan Great Zimbabwe. Ibukotanya adalah Harare.',
      'lesotho': 'Lesotho adalah negara pegunungan yang seluruhnya terletak di dalam Afrika Selatan. Ibukotanya adalah Maseru.',
      'eswatini': 'Eswatini (sebelumnya Swaziland) adalah negara kecil di Afrika bagian selatan. Ibukotanya adalah Mbabane.',
      'comoros': 'Komoro adalah negara kepulauan di Samudra Hindia antara Mozambik dan Madagaskar. Ibukotanya adalah Moroni.',
      'cape verde': 'Tanjung Verde (Cape Verde) adalah negara kepulauan di Samudra Atlantik. Ibukotanya adalah Praia.',
      'seychelles': 'Seychelles adalah negara kepulauan di Samudra Hindia dengan pantai eksotis dan wisata mewah. Ibukotanya adalah Victoria.',
      'new zealand': 'Selandia Baru adalah negara di Pasifik Selatan yang terkenal dengan pemandangan alam dramatis, Maori, dan lokasi syuting The Lord of the Rings. Ibukotanya adalah Wellington.',
      'micronesia': 'Mikronesia adalah negara kepulauan di Samudra Pasifik barat dengan banyak atol dan pulau karang. Ibukotanya adalah Palikir.',
      'marshall islands': 'Kepulauan Marshall adalah negara kepulauan di Samudra Pasifik yang terkenal dengan laguna besar dan sejarah uji nuklir. Ibukotanya adalah Majuro.',
      'palau': 'Palau adalah negara kepulauan di Samudra Pasifik barat, terkenal dengan penyelaman scuba dan karang. Ibukotanya adalah Ngerulmud.',
      'solomon islands': 'Kepulauan Solomon adalah negara di Samudra Pasifik yang terkenal dengan pertempuran Perang Dunia II. Ibukotanya adalah Honiara.',
      'tonga': 'Tonga adalah kerajaan di Pasifik Selatan dengan budaya Polinesia yang kaya. Ibukotanya adalah Nukuʻalofa.',
      'samoa barat': 'Samoa Barat (Samoa) adalah negara di Pasifik Selatan dengan budaya Polinesia. Ibukotanya adalah Apia.',
      'vatican city': 'Vatikan adalah negara terkecil di dunia, pusat Gereja Katolik, tempat tinggal Paus. Terletak di Roma.',
      'monaco': 'Monako adalah negara kota kecil di Mediterania, terkenal dengan kasino Monte Carlo dan balapan F1.',
      'andorra': 'Andorra adalah negara kecil di Pegunungan Pyrenees antara Prancis dan Spanyol, terkenal dengan resor ski.',
      'san marino': 'San Marino adalah republik kecil di Italia, salah satu negara tertua di dunia.',
      'liechtenstein': 'Liechtenstein adalah negara kecil di Eropa Tengah antara Swiss dan Austria, terkenal dengan industri keuangan.',
      'iceland': 'Islandia adalah negara pulau di Atlantik Utara, terkenal dengan gunung berapi, geyser, dan aurora. Ibukotanya adalah Reykjavik.',
      'greenland': 'Greenland adalah pulau terbesar di dunia, wilayah otonom Denmark dengan lanskap es luas. Ibukotanya adalah Nuuk.',
      'faroes': 'Kepulauan Faroe adalah wilayah otonom Denmark di Samudra Atlantik Utara dengan tebing laut dramatis. Ibukotanya adalah Torshavn.',
      'uni emirat arab': 'Uni Emirat Arab (UEA) adalah negara federasi di Timur Tengah yang terdiri dari tujuh emirat, termasuk Dubai dan Abu Dhabi. Negara ini terkenal dengan pencakar langit megah, industri pariwisata mewah, dan cadangan minyak.',
      'oman': 'Oman adalah negara di Semenanjung Arab yang terkenal dengan padang pasir, pegunungan, dan garis pantai panjang di Laut Arab. Ibukotanya adalah Muscat.',
      'vietnam': 'Vietnam adalah negara di Asia Tenggara yang terkenal dengan Teluk Ha Long, sawah hijau, dan sejarah Perang Vietnam. Ibukotanya adalah Hanoi.',
      'thailand': 'Thailand adalah negara di Asia Tenggara yang terkenal dengan kuil Buddha, pantai tropis, dan budaya kuliner. Ibukotanya adalah Bangkok.',
      'philippines': 'Filipina adalah negara kepulauan di Asia Tenggara dengan ribuan pulau tropis. Ibukotanya adalah Manila.',
      'singapore': 'Singapura adalah negara kota di Asia Tenggara yang terkenal dengan pelabuhan tersibuk, taman futuristik, dan kota modern bersih. Ibukotanya adalah Singapura.',
      'south korea': 'Korea Selatan adalah negara di Asia Timur terkenal dengan teknologi maju, budaya pop K-Pop, dan drama Korea. Ibukotanya adalah Seoul.',
      'north korea': 'Korea Utara adalah negara di Asia Timur yang terkenal dengan rezim tertutup dan pemerintahan otoriter. Ibukotanya adalah Pyongyang.',
      'bangladesh': 'Bangladesh adalah negara di Asia Selatan dengan Sungai Gangga dan Brahmaputra. Ibukotanya adalah Dhaka.',
      'sri lanka': 'Sri Lanka adalah negara pulau di selatan India yang terkenal dengan pantai, kuil Buddha, dan kebun teh. Ibukotanya adalah Sri Jayawardenepura Kotte.',
      'nepal': 'Nepal adalah negara di Asia Selatan yang terletak di Himalaya, rumah bagi Gunung Everest. Ibukotanya adalah Kathmandu.',
      'bhutan': 'Bhutan adalah negara kecil di Himalaya yang terkenal dengan kebahagiaan nasional dan biara di tebing. Ibukotanya adalah Thimphu.',
      'malawi': 'Malawi adalah negara di Afrika bagian tenggara yang terkenal dengan Danau Malawi, salah satu danau terbesar di Afrika. Ibukotanya adalah Lilongwe.',
      'mozambique': 'Mozambik adalah negara di Afrika bagian tenggara yang memiliki pantai Samudra Hindia yang panjang. Ibukotanya adalah Maputo.',
      'madagascar': 'Madagaskar adalah pulau besar di lepas pantai Afrika, terkenal dengan flora dan fauna unik seperti lemur. Ibukotanya adalah Antananarivo.',
      'mauritania': 'Mauritania adalah negara di Afrika Barat Laut yang sebagian besar wilayahnya gurun Sahara. Ibukotanya adalah Nouakchott.',
      'niger': 'Niger adalah negara di Afrika Barat yang sebagian besar gurun Sahara. Ibukotanya adalah Niamey.',
      'chad': 'Chad adalah negara di Afrika Tengah yang terkenal dengan Danau Chad dan Gurun Sahara di utara. Ibukotanya adalah N\'Djamena.',
      'central african republic': 'Republik Afrika Tengah adalah negara di jantung Afrika dengan keanekaragaman hayati dan sumber daya alam. Ibukotanya adalah Bangui.',
      'gabon': 'Gabon adalah negara di Afrika Tengah dengan hutan hujan lebat dan satwa liar langka. Ibukotanya adalah Libreville.',
      'republic of the congo': 'Republik Kongo adalah negara di Afrika Tengah, berbatasan dengan Sungai Kongo. Ibukotanya adalah Brazzaville.',
      'democratic republic of the congo': 'Republik Demokratik Kongo adalah salah satu negara terbesar di Afrika dengan Sungai Kongo yang besar. Ibukotanya adalah Kinshasa.',
      'equatorial guinea': 'Guinea Khatulistiwa adalah negara kecil di Afrika Tengah dengan cadangan minyak. Ibukotanya adalah Malabo.',
      'sao tome and principe': 'Sao Tome dan Principe adalah negara kepulauan kecil di Teluk Guinea, Afrika Tengah. Ibukotanya adalah Sao Tome.',
      'gambia': 'Gambia adalah negara kecil di Afrika Barat yang dikelilingi Senegal. Ibukotanya adalah Banjul.',
      'guinea': 'Guinea adalah negara di Afrika Barat dengan sumber daya alam besar. Ibukotanya adalah Conakry.',
      'guinea bissau': 'Guinea Bissau adalah negara kecil di Afrika Barat yang terkenal dengan kepulauan Bijagos. Ibukotanya adalah Bissau.',
      'sierra leone': 'Sierra Leone adalah negara di Afrika Barat terkenal dengan pantai Atlantik dan sejarah perdagangan budak. Ibukotanya adalah Freetown.',
      'liberia': 'Liberia adalah negara di Afrika Barat yang didirikan oleh budak Afrika yang kembali dari Amerika. Ibukotanya adalah Monrovia.',
      'benin': 'Benin adalah negara di Afrika Barat dengan sejarah Kerajaan Dahomey. Ibukotanya adalah Porto-Novo.',
      'togo': 'Togo adalah negara kecil di Afrika Barat dengan pantai pendek di Teluk Guinea. Ibukotanya adalah Lomé.',
      'burkina faso': 'Burkina Faso adalah negara di Afrika Barat yang terkenal dengan budaya musik dan seni. Ibukotanya adalah Ouagadougou.',
      'yaman': 'Yaman adalah negara di ujung selatan Semenanjung Arab, dengan sejarah kuno Kerajaan Saba. Ibukotanya adalah Sana\'a.',
      'pakistan': 'Pakistan adalah negara di Asia Selatan yang berbatasan dengan India, Afghanistan, Iran, dan China. Ibukotanya adalah Islamabad.',
      'afghanistan': 'Afghanistan adalah negara di Asia Tengah yang terkenal dengan pegunungan Hindu Kush dan sejarah panjang sebagai jalur perdagangan Jalur Sutra. Ibukotanya adalah Kabul.',
      'iran': 'Iran adalah negara di Asia Barat yang kaya sejarah Persia kuno, terkenal dengan arsitektur indah dan kebudayaan sastra. Ibukotanya adalah Teheran.',
      'syria': 'Suriah adalah negara di Timur Tengah dengan warisan sejarah kuno, termasuk kota Damaskus, salah satu kota tertua yang terus dihuni. Ibukotanya adalah Damaskus.',
      'palestina': 'Palestina adalah wilayah di Timur Tengah yang mencakup Tepi Barat dan Jalur Gaza. Ibukota de facto yang diakui adalah Ramallah, meskipun Yerusalem Timur juga diklaim, FREE PALESTIN.',
      'saudi arabia': 'Arab Saudi adalah negara terbesar di Semenanjung Arab yang terkenal dengan Mekkah dan Madinah, dua kota suci umat Islam. Ibukotanya adalah Riyadh.',
      'kazakhstan': 'Kazakhstan adalah negara di Asia Tengah dengan wilayah luas, terkenal dengan padang stepa dan kota modern Astana (Nur-Sultan).',
      'uzbekistan': 'Uzbekistan adalah negara di Asia Tengah yang kaya sejarah Jalur Sutra, memiliki kota bersejarah Samarkand dan Bukhara. Ibukotanya adalah Tashkent.',
      'kyrgyzstan': 'Kirgistan adalah negara pegunungan di Asia Tengah dengan warisan budaya nomaden. Ibukotanya adalah Bishkek.',
      'tajikistan': 'Tajikistan adalah negara pegunungan di Asia Tengah dengan mayoritas penduduk Tajik. Ibukotanya adalah Dushanbe.',
      'turkmenistan': 'Turkmenistan adalah negara di Asia Tengah yang terkenal dengan gurun Karakum dan pintu Neraka Darvaza. Ibukotanya adalah Ashgabat.',
      'laos': 'Laos adalah negara di Asia Tenggara yang terkurung daratan, terkenal dengan Sungai Mekong dan kota Luang Prabang yang bersejarah. Ibukotanya adalah Vientiane.',
      'cambodia': 'Kamboja adalah negara di Asia Tenggara yang terkenal dengan Candi Angkor Wat. Ibukotanya adalah Phnom Penh.',
      'myanmar': 'Myanmar atau Burma adalah negara di Asia Tenggara dengan situs budaya kuno seperti Bagan. Ibukotanya adalah Naypyidaw.',
      'brunei': 'Brunei adalah negara kecil kaya minyak di pulau Kalimantan. Ibukotanya adalah Bandar Seri Begawan.',
      'denmark': 'Denmark adalah negara Nordik di Eropa Utara yang dikenal dengan standar hidup tinggi, kesejahteraan sosial, dan kota-kota yang ramah sepeda. Ibukotanya adalah Kopenhagen, kota modern dengan pelabuhan berwarna-warni Nyhavn dan Istana Amalienborg. Denmark terkenal sebagai salah satu negara paling bahagia di dunia, memiliki sistem pendidikan dan kesehatan yang baik. Budaya Denmark mencakup desain minimalis, filosofi hygge (kenyamanan sederhana), dan warisan dongeng Hans Christian Andersen.',
      'islandia': 'Islandia adalah negara pulau di Samudra Atlantik Utara yang terkenal dengan keajaiban alamnya seperti geyser, air terjun, gunung berapi, dan pemandian air panas. Ibukotanya adalah Reykjavik, kota paling utara di dunia. Islandia memiliki populasi kecil tetapi terkenal dengan kualitas hidup tinggi dan alam yang terjaga. Negara ini menjadi tujuan wisata populer untuk melihat Aurora Borealis dan menjelajah lanskap dramatisnya.',
      'polandia': 'Polandia adalah negara di Eropa Tengah dengan sejarah panjang dan budaya yang kaya. Ibukotanya adalah Warsawa, kota yang pernah hancur total pada Perang Dunia II namun dibangun kembali dengan megah. Kota bersejarah Krakow terkenal dengan arsitektur Gotik dan Renaisansnya. Polandia dikenal dengan warisan musik klasik, kuliner khas seperti pierogi, serta situs bersejarah seperti bekas kamp Auschwitz yang menjadi pengingat tragedi Holocaust.',
      'seychelles': 'Seychelles adalah negara kepulauan di Samudra Hindia yang terkenal dengan pantai berpasir putih, air laut jernih, dan keanekaragaman hayati lautnya. Ibukotanya adalah Victoria, salah satu ibu kota terkecil di dunia. Seychelles menjadi tujuan wisata mewah dengan ekowisata yang terjaga.',
      'mauritius': 'Mauritius adalah negara pulau di Samudra Hindia timur Madagaskar, terkenal dengan pantai tropis, laguna, dan terumbu karang. Ibukotanya adalah Port Louis. Negara ini memiliki penduduk multietnis dan warisan kolonial Prancis-Inggris.',
      'maldives': 'Maladewa adalah negara kepulauan di Samudra Hindia yang terkenal dengan resor mewah di pulau-pulau karang, pantai pasir putih, dan laut biru jernih. Ibukotanya adalah Malé. Pariwisata dan perikanan adalah penopang utama ekonomi.',
      'fiji': 'Fiji adalah negara kepulauan di Samudra Pasifik Selatan yang terkenal dengan pantai tropis, terumbu karang, dan budaya Polinesia. Ibukotanya adalah Suva. Fiji menjadi tujuan wisata populer untuk menyelam dan berselancar.',
      'samoa': 'Samoa adalah negara kepulauan di Pasifik Selatan yang memiliki budaya Polinesia kuat. Ibukotanya adalah Apia. Samoa terkenal dengan pantai indah, air terjun, dan tradisi keluarga yang kental.',
      'kiribati': 'Kiribati adalah negara kepulauan terpencil di Pasifik Tengah yang terdiri dari 33 atol dan pulau karang. Ibukotanya adalah Tarawa Selatan. Kiribati menghadapi tantangan perubahan iklim karena naiknya permukaan laut.',
      'nauru': 'Nauru adalah republik pulau terkecil ketiga di dunia, terletak di Pasifik Tengah. Tidak memiliki ibu kota resmi, tetapi pusat pemerintahan di Yaren. Nauru terkenal dengan sejarah tambang fosfatnya.',
      'tuvalu': 'Tuvalu adalah negara kepulauan kecil di Samudra Pasifik yang dikenal sebagai salah satu negara berpenduduk paling sedikit di dunia. Ibukotanya adalah Funafuti. Tuvalu juga rentan tenggelam akibat naiknya permukaan laut.',
      'vanuatu': 'Vanuatu adalah negara kepulauan di Pasifik Selatan yang terkenal dengan budaya Melanesia, aktivitas vulkanik, dan situs selam bangkai kapal. Ibukotanya adalah Port Vila.',
      'papua nugini': 'Papua Nugini terletak di Pasifik Barat Daya, berbatasan darat dengan Papua (Indonesia). Ibukotanya adalah Port Moresby. Papua Nugini terkenal dengan keanekaragaman budaya dan bahasa yang luar biasa.',
      'timor leste': 'Timor Leste atau Timor Timur adalah negara di Asia Tenggara yang merdeka dari Indonesia pada 2002. Ibukotanya adalah Dili. Negara ini dikenal dengan pantai alami dan budaya campuran Portugis-Timor.',
      'mongolia': 'Mongolia adalah negara di Asia Timur terkurung daratan, terkenal dengan dataran stepa, budaya nomaden, dan sejarah Jenghis Khan. Ibukotanya adalah Ulaanbaatar.',
      'armenia': 'Armenia adalah negara di Kaukasus yang terkurung daratan, terkenal dengan sejarah Kristen kuno dan biara-biara indah. Ibukotanya adalah Yerevan.',
      'belarus': 'Belarus adalah negara di Eropa Timur yang berbatasan dengan Rusia, Ukraina, Polandia, Lithuania, dan Latvia. Ibukotanya adalah Minsk.',
      'moldova': 'Moldova adalah negara kecil di Eropa Timur yang terkenal dengan kebun anggur dan budaya campuran Rumania-Rusia. Ibukotanya adalah Chisinau.',
      'cyprus': 'Siprus adalah negara pulau di Mediterania Timur dengan sejarah Yunani dan Turki. Ibukotanya adalah Nicosia.',
      'lebanon': 'Lebanon adalah negara di Timur Tengah di tepi Laut Mediterania, terkenal dengan sejarah kuno Fenisia. Ibukotanya adalah Beirut.',
      'jordan': 'Yordania adalah negara di Timur Tengah yang terkenal dengan situs Petra, Gurun Wadi Rum, dan Laut Mati. Ibukotanya adalah Amman.',
      'kuwait': 'Kuwait adalah negara kecil di Teluk Persia dengan cadangan minyak besar. Ibukotanya adalah Kuwait City.',
      'bahrain': 'Bahrain adalah negara kepulauan kecil di Teluk Persia yang terkenal sebagai pusat keuangan dan perbankan di Timur Tengah. Ibukotanya adalah Manama.',
      'uganda': 'Uganda adalah negara di Afrika Timur yang terkenal dengan Danau Victoria dan keanekaragaman hayati termasuk gorila gunung di Taman Nasional Bwindi. Ibukotanya adalah Kampala. Uganda juga dikenal sebagai Mutiara Afrika karena keindahan alamnya, Sungai Nil yang mengalir melintasi negara ini, serta satwa liar yang menarik wisatawan.',
      'ghana': 'Ghana adalah negara di Afrika Barat yang terkenal dengan pantai emas, kastil-kastil bersejarah di pesisir, dan sejarah perdagangan emas dan budak. Ibukotanya adalah Accra. Ghana memiliki demokrasi yang stabil di Afrika dan budaya musik serta tarian yang meriah.',
      'aljazair': 'Aljazair adalah negara terbesar di Afrika berdasarkan luas wilayah. Terletak di Afrika Utara, Aljazair memiliki wilayah gurun Sahara yang luas. Ibukotanya adalah Algiers. Negara ini memiliki warisan arsitektur Ottoman, pantai Mediterania, dan pegunungan Atlas.',
      'tunisia': 'Tunisia adalah negara di Afrika Utara yang berbatasan dengan Laut Mediterania. Ibukotanya adalah Tunis. Tunisia memiliki situs sejarah seperti reruntuhan Kartago, kota tua Medina, dan gurun Sahara. Negara ini juga dikenal sebagai salah satu lokasi syuting film Star Wars.',
      'sudan': 'Sudan adalah negara di Afrika Timur Laut yang terletak di sepanjang Sungai Nil. Ibukotanya adalah Khartoum. Sudan memiliki piramida kuno di Meroë, peninggalan Kerajaan Kush. Negara ini memiliki sejarah panjang dan keragaman budaya Arab dan Afrika.',
      'senegal': 'Senegal adalah negara di Afrika Barat dengan ibukota Dakar. Negara ini terkenal dengan Pulau Gorée, situs sejarah perdagangan budak, dan musik mbalax yang mendunia. Senegal memiliki tradisi budaya yang kaya dan dikenal dengan keramahan penduduknya.',
      'angola': 'Angola adalah negara di Afrika bagian selatan yang memiliki cadangan minyak dan berlian yang besar. Ibukotanya adalah Luanda, salah satu kota pelabuhan utama di Afrika. Angola memiliki pantai Atlantik yang indah dan warisan budaya Portugis.',
      'tanzania': 'Tanzania adalah negara di Afrika Timur yang terkenal dengan Taman Nasional Serengeti, Gunung Kilimanjaro, dan Kepulauan Zanzibar. Ibukotanya adalah Dodoma, meskipun pusat komersialnya adalah Dar es Salaam. Tanzania adalah tujuan utama safari di Afrika.',
      'botswana': 'Botswana adalah negara di Afrika bagian selatan yang dikenal dengan satwa liar dan Delta Okavango, salah satu ekosistem delta pedalaman terbesar di dunia. Ibukotanya adalah Gaborone. Botswana memiliki kebijakan konservasi yang baik dan pariwisata safari premium.',
      'namibia': 'Namibia adalah negara di Afrika bagian selatan yang terkenal dengan Gurun Namib, salah satu gurun tertua di dunia. Ibukotanya adalah Windhoek. Namibia memiliki lanskap gurun, ngarai Fish River, dan Taman Nasional Etosha.',
      'zambia': 'Zambia adalah negara di Afrika bagian selatan yang terkenal dengan Air Terjun Victoria, yang dibagi dengan Zimbabwe. Ibukotanya adalah Lusaka. Zambia memiliki banyak taman nasional dan dikenal sebagai tujuan safari dengan satwa liar yang beragam.',
      'jamaika': 'Jamaika adalah negara pulau di Karibia yang terkenal dengan musik reggae, pantai tropis, dan pelari cepat dunia seperti Usain Bolt. Ibukotanya adalah Kingston. Jamaika memiliki budaya yang kuat dengan pengaruh Afrika, Eropa, dan India.',
      'bahama': 'Bahama adalah negara kepulauan di Samudra Atlantik yang terkenal dengan pantai berpasir putih dan resor mewah. Ibukotanya adalah Nassau. Bahama menjadi tujuan wisata populer untuk penyelaman, snorkeling, dan pelayaran pesiar.',
      'kuba': 'Kuba adalah negara pulau di Karibia yang terkenal dengan sejarah revolusinya di bawah Fidel Castro. Ibukotanya adalah Havana, kota bersejarah dengan arsitektur kolonial dan mobil klasik. Kuba terkenal dengan musik salsa, cerutu, dan pantai Varadero.',
      'haiti': 'Haiti adalah negara pulau di Karibia yang berbagi pulau Hispaniola dengan Republik Dominika. Ibukotanya adalah Port-au-Prince. Haiti memiliki sejarah unik sebagai republik kulit hitam merdeka pertama di dunia setelah pemberontakan budak pada abad ke-18.',
      'republik dominika': 'Republik Dominika terletak di Karibia dan berbagi pulau Hispaniola dengan Haiti. Ibukotanya adalah Santo Domingo, kota tertua di Amerika yang didirikan oleh orang Eropa. Negara ini terkenal dengan pantai Punta Cana dan budaya merengue.',
      'panama': 'Panama adalah negara di Amerika Tengah yang terkenal dengan Terusan Panama, jalur air strategis yang menghubungkan Samudra Atlantik dan Pasifik. Ibukotanya adalah Panama City. Negara ini memiliki ekonomi berbasis jasa, pelabuhan, dan pariwisata.',
      'costa rica': 'Costa Rica adalah negara di Amerika Tengah yang terkenal dengan keanekaragaman hayati, hutan hujan tropis, dan kebijakan pelestarian lingkungan. Ibukotanya adalah San José. Costa Rica memiliki reputasi sebagai negara damai tanpa angkatan bersenjata.',
      'guatemala': 'Guatemala adalah negara di Amerika Tengah yang memiliki warisan peradaban Maya kuno. Ibukotanya adalah Guatemala City. Negara ini memiliki situs arkeologi terkenal seperti Tikal, pegunungan vulkanik, dan budaya campuran Maya-Spanyol.',
      'honduras': 'Honduras adalah negara di Amerika Tengah yang terkenal dengan pantai Karibia, Pulau Roatán, dan situs reruntuhan Maya Copán. Ibukotanya adalah Tegucigalpa. Honduras memiliki keanekaragaman hayati dan pariwisata alam yang berkembang.',
      'hungaria': 'Hungaria adalah negara di Eropa Tengah yang terkenal dengan Sungai Danube yang membelah ibu kotanya, Budapest. Budapest dikenal dengan jembatan indah, pemandian air panas, dan bangunan bergaya Art Nouveau. Hungaria memiliki warisan budaya yang kaya dalam musik, sastra, dan kuliner seperti goulash. Negara ini pernah menjadi bagian dari Kekaisaran Austro-Hungaria dan memiliki banyak istana serta benteng bersejarah.',
      'el salvador': 'El Salvador adalah negara terkecil di Amerika Tengah dengan garis pantai di Samudra Pasifik. Ibukotanya adalah San Salvador. Negara ini terkenal dengan pantai selancar seperti El Tunco, gunung berapi, dan kopi berkualitas. Ekonominya bertumpu pada remitansi dan pertanian.',
      'nicaragua': 'Nikaragua adalah negara di Amerika Tengah yang terkenal dengan danau, gunung berapi aktif, dan kota kolonial Granada. Ibukotanya adalah Managua. Nikaragua memiliki budaya yang kaya dengan tradisi musik, tarian, dan festival rakyat.',
      'belize': 'Belize adalah negara kecil di Amerika Tengah yang terkenal dengan terumbu karang terbesar kedua di dunia, Belize Barrier Reef. Ibukotanya adalah Belmopan. Negara ini memiliki hutan hujan tropis, reruntuhan Maya, dan pariwisata laut yang berkembang.',
      'paraguay': 'Paraguay adalah negara yang terkurung daratan di Amerika Selatan, berbatasan dengan Argentina, Brasil, dan Bolivia. Ibukotanya adalah Asunción. Paraguay memiliki budaya campuran Spanyol dan Guarani serta sungai Paraguay yang vital untuk transportasi.',
      'uruguay': 'Uruguay adalah negara di Amerika Selatan yang terkenal dengan pantai Atlantik, kehidupan santai, dan reputasi demokrasi stabil. Ibukotanya adalah Montevideo. Uruguay terkenal dengan budaya mate, tango, dan sepak bolanya.',
      'bolivia': 'Bolivia adalah negara di Amerika Selatan yang terkurung daratan dan memiliki lanskap beragam dari Pegunungan Andes hingga Gurun Garam Salar de Uyuni. Ibukotanya secara administratif adalah Sucre, sedangkan pusat pemerintahan adalah La Paz.',
      'ecuador': 'Ekuador adalah negara di Amerika Selatan yang terkenal dengan Kepulauan Galapagos, Andes, dan Hutan Amazon. Ibukotanya adalah Quito. Ekuador terletak di garis khatulistiwa, sehingga namanya berarti EQUATOR', 
      'suriname': 'Suriname adalah negara terkecil di Amerika Selatan, dengan ibukota Paramaribo. Negara ini memiliki hutan hujan tropis yang luas dan populasi multietnis dengan pengaruh budaya India, Jawa, Afrika, dan Belanda',
      'guyana': 'Guyana adalah negara di Amerika Selatan yang berbatasan dengan Laut Karibia. Ibukotanya adalah Georgetown. Guyana memiliki keanekaragaman hayati yang kaya dengan sungai, air terjun Kaieteur, dan hutan hujan lebat.',
      'luxembourg': 'Luksemburg adalah negara kecil di Eropa Barat yang dikenal sebagai pusat keuangan internasional. Ibukotanya adalah Luxembourg City. Negara ini memiliki kastil abad pertengahan, hutan hijau, dan kualitas hidup tinggi.',
      'liechtenstein': 'Liechtenstein adalah negara kecil di Eropa Tengah yang terletak di antara Swiss dan Austria. Ibukotanya adalah Vaduz. Negara ini terkenal dengan pegunungan Alpen, industri keuangan, dan sebagai pusat bisnis internasional.',
      'monaco': 'Monako adalah negara kota kecil di pantai Mediterania yang terkenal dengan kemewahan, kasino Monte Carlo, dan balapan Formula 1. Ibukotanya adalah Monaco-Ville. Monako memiliki salah satu populasi terkaya di dunia.',
      'andorra': 'Andorra adalah negara kecil di Pegunungan Pyrenees antara Prancis dan Spanyol. Ibukotanya adalah Andorra la Vella. Negara ini terkenal dengan resor ski dan status bebas pajak yang menarik wisatawan.',
      'san marino': 'San Marino adalah republik independen terkecil ketiga di Eropa, terletak di Italia. Ibukotanya adalah Kota San Marino. Negara ini terkenal dengan benteng abad pertengahan di puncak gunung dan menjadi salah satu negara tertua di dunia.',
      'malta': 'Malta adalah negara kepulauan di Laut Mediterania yang terkenal dengan situs arkeologi prasejarah, kota berdinding Valletta, dan pelabuhan alami yang indah. Ibukotanya adalah Valletta. Malta memiliki sejarah panjang sebagai benteng penting di jalur perdagangan Mediterania.',
      'singapura': 'Singapura adalah negara kota di Asia Tenggara yang terkenal sebagai pusat keuangan, perdagangan, dan transportasi dunia. Negara ini memiliki standar hidup yang sangat tinggi dengan sistem pemerintahan yang efisien dan keamanan yang baik. Ikon terkenal Singapura adalah Marina Bay Sands, Gardens by the Bay, dan patung Merlion. Singapura memiliki penduduk multikultural dengan tiga kelompok etnis utama: Tionghoa, Melayu, dan India. Meskipun wilayahnya kecil, Singapura berperan besar di kancah internasional.',
      'nepal': 'Nepal adalah negara di Asia Selatan yang terletak di kaki Pegunungan Himalaya. Ibukotanya adalah Kathmandu. Nepal terkenal sebagai rumah bagi Gunung Everest, puncak tertinggi di dunia, dan merupakan destinasi populer untuk pendaki gunung. Negara ini memiliki warisan budaya yang kaya dengan banyak kuil Hindu dan Buddha. Nepal juga terkenal dengan keragaman etnis dan festival tradisionalnya.',
      'bangladesh': 'Bangladesh adalah negara di Asia Selatan yang berbatasan dengan India dan Myanmar. Ibukotanya adalah Dhaka. Bangladesh terkenal sebagai salah satu negara dengan kepadatan penduduk tertinggi di dunia. Negara ini memiliki ekonomi yang bertumpu pada industri tekstil dan pertanian. Sungai Gangga dan Brahmaputra membentuk delta sungai terbesar di dunia yang sangat subur.',
      'mongolia': 'Mongolia adalah negara di Asia Timur yang terkurung daratan, terletak di antara Rusia dan China. Ibukotanya adalah Ulaanbaatar. Mongolia terkenal dengan dataran luas, padang rumput stepa, dan budaya penggembala nomaden. Negara ini memiliki warisan sejarah dari Kekaisaran Mongol di bawah Jenghis Khan. Wisata padang rumput Gobi dan festival Naadam menarik banyak pengunjung.',
      'azerbaijan': 'Azerbaijan adalah negara di kawasan Kaukasus yang terletak di perbatasan Eropa dan Asia. Ibukotanya adalah Baku, kota modern di tepi Laut Kaspia. Azerbaijan dikenal sebagai negara kaya minyak dengan budaya campuran Eropa dan Timur Tengah. Negara ini memiliki arsitektur modern berpadu dengan benteng kuno, serta tradisi musik mugham.',
      'georgia': 'Georgia adalah negara di wilayah Kaukasus yang terletak di persimpangan Eropa Timur dan Asia Barat. Ibukotanya adalah Tbilisi. Georgia terkenal dengan pegunungan Kaukasus, anggur tradisionalnya yang diakui sebagai salah satu yang tertua di dunia, serta budaya ramah tamahnya. Negara ini memiliki situs warisan dunia seperti Biara Gelati.',
      'serbia': 'Serbia adalah negara di Eropa Tenggara yang dulunya merupakan bagian dari Yugoslavia. Ibukotanya adalah Beograd (Belgrade). Serbia terkenal dengan sejarah panjangnya, arsitektur bergaya Ottoman dan Eropa Timur, serta musik folk tradisional. Negara ini terletak di jalur strategis Balkan dengan budaya campuran Eropa dan Timur Tengah.',
      'kroasia': 'Kroasia adalah negara di Eropa Tenggara yang terletak di tepi Laut Adriatik. Ibukotanya adalah Zagreb. Kroasia terkenal dengan keindahan pantai, pulau-pulaunya, dan kota tua Dubrovnik yang menjadi lokasi syuting serial Game of Thrones. Negara ini memiliki pariwisata sebagai sektor ekonomi utama.',
      'slowakia': 'Slowakia adalah negara di Eropa Tengah yang berbatasan dengan Polandia, Republik Ceko, Austria, Hungaria, dan Ukraina. Ibukotanya adalah Bratislava. Slowakia dikenal dengan pegunungan Tatra, kastil abad pertengahan, dan desa-desa tradisionalnya. Negara ini juga merupakan bagian dari Uni Eropa dan zona euro.',
      'slovenia': 'Slovenia adalah negara kecil di Eropa Tengah yang terkenal dengan keindahan alamnya, danau Bled yang indah, gua karst, dan Pegunungan Alpen Julian. Ibukotanya adalah Ljubljana. Slovenia memiliki kualitas hidup yang tinggi dan menjadi destinasi wisata alam yang populer.',
      'czech republic': 'Republik Ceko (Czech Republic) adalah negara di Eropa Tengah yang terkenal dengan kota Praha (Prague), ibukota yang memukau dengan kastil, jembatan bersejarah, dan alun-alun tua. Negara ini dikenal dengan birnya yang mendunia, arsitektur Gotik dan Barok, serta festival seni dan budaya.',
      'romania': 'Rumania adalah negara di Eropa Timur yang terkenal dengan Pegunungan Carpathian dan wilayah Transylvania yang identik dengan legenda Dracula. Ibukotanya adalah Bucharest. Rumania memiliki kastil bersejarah seperti Kastil Bran, desa-desa kuno, dan pemandangan alam yang indah.',
      'bulgaria': 'Bulgaria adalah negara di Eropa Tenggara yang terletak di Semenanjung Balkan. Ibukotanya adalah Sofia. Bulgaria memiliki sejarah panjang yang mencakup pengaruh Kekaisaran Romawi dan Ottoman. Negara ini terkenal dengan biara-biara kuno, pantai Laut Hitam, dan pegunungan Pirin dan Rila.',
      'madagaskar': 'Madagaskar adalah negara pulau besar di lepas pantai timur Afrika yang terkenal dengan keanekaragaman hayati uniknya. Ibukotanya adalah Antananarivo. Sekitar 90% spesies tumbuhan dan hewan di Madagaskar tidak ditemukan di tempat lain di dunia. Negara ini terkenal dengan lemur, baobab, dan Taman Nasional yang indah.',
      'zimbabwe': 'Zimbabwe adalah negara di Afrika bagian selatan yang terkenal dengan Air Terjun Victoria, salah satu air terjun terbesar di dunia. Ibukotanya adalah Harare. Zimbabwe memiliki situs arkeologi kuno seperti Great Zimbabwe, bekas pusat Kerajaan Zimbabwe. Ekonomi negara ini berbasis pertanian, pertambangan, dan pariwisata.',
      'ethiopia': 'Ethiopia adalah negara di Tanduk Afrika yang terkenal sebagai salah satu peradaban tertua di dunia. Ibukotanya adalah Addis Ababa. Ethiopia memiliki sejarah Kekaisaran Aksum, gereja-gereja batu Lalibela, dan pemandangan alam Pegunungan Simien. Negara ini juga dikenal sebagai tempat asal kopi.',
      'uae': 'Uni Emirat Arab (UAE) adalah negara federasi di Jazirah Arab yang terkenal dengan gedung pencakar langit ikonik Burj Khalifa di Dubai. Ibukotanya adalah Abu Dhabi. UAE kaya akan cadangan minyak dan gas, dan kini berkembang pesat di sektor pariwisata, keuangan, dan teknologi. Dubai dikenal sebagai destinasi belanja mewah dan inovasi arsitektur modern.',
      'ukraina': 'Ukraina adalah negara terbesar di Eropa setelah Rusia, terletak di Eropa Timur. Ibukotanya adalah Kyiv. Ukraina memiliki sejarah panjang dan merupakan pusat peradaban Slavia Timur. Negara ini dikenal dengan dataran luasnya, pertanian gandum, dan situs bersejarah seperti Katedral St. Sophia. Ukraina menjadi sorotan dunia karena konflik geopolitik dengan Rusia.',
      'kolombia': 'Kolombia adalah negara di Amerika Selatan yang terkenal dengan keindahan alamnya mulai dari pegunungan Andes, hutan Amazon, hingga pantai Karibia. Ibukotanya adalah Bogotá. Kolombia dikenal dengan kopi berkualitas tinggi, musik cumbia dan vallenato, serta festival bunga Medellin. Meskipun pernah menghadapi konflik internal, kini Kolombia menjadi destinasi wisata budaya dan alam.',
      'kenya': 'Kenya adalah negara di Afrika Timur yang terkenal dengan sabana, satwa liar, dan Taman Nasional Maasai Mara. Ibukotanya adalah Nairobi. Kenya menjadi salah satu destinasi safari paling populer di dunia dengan hewan-hewan seperti singa, gajah, dan jerapah. Negara ini juga dikenal dengan atlet lari jarak jauhnya yang mendunia.',
      'nigeria': 'Nigeria adalah negara terpadat di Afrika yang terletak di Afrika Barat. Ibukotanya adalah Abuja, sedangkan kota terbesarnya adalah Lagos, pusat ekonomi dan budaya. Nigeria memiliki keragaman etnis yang besar dengan suku Yoruba, Hausa, dan Igbo sebagai kelompok utama. Negara ini kaya akan minyak bumi dan gas alam. Industri musik Nigeria, seperti Afrobeats, mendunia.',
      'venezuela': 'Venezuela adalah negara di Amerika Selatan yang memiliki cadangan minyak bumi terbesar di dunia. Ibukotanya adalah Caracas. Negara ini terkenal dengan pemandangan spektakuler seperti Air Terjun Angel, air terjun tertinggi di dunia. Venezuela memiliki keanekaragaman hayati yang tinggi dan pernah menjadi salah satu negara terkaya di kawasan ini sebelum krisis ekonomi.',
      'peru': 'Peru adalah negara di Amerika Selatan yang terkenal dengan situs Machu Picchu peninggalan Kerajaan Inca. Ibukotanya adalah Lima. Peru memiliki warisan budaya yang kaya dengan perpaduan budaya Inca dan kolonial Spanyol. Negara ini juga memiliki keanekaragaman hayati mulai dari Pegunungan Andes, hutan hujan Amazon, hingga garis pantai Pasifik.',
      'srilanka': 'Sri Lanka adalah negara pulau di Asia Selatan yang terletak di selatan India. Ibukotanya adalah Colombo (komersial) dan Sri Jayawardenepura Kotte (administratif). Sri Lanka terkenal dengan perkebunan teh, pantai tropis, dan situs bersejarah Buddha seperti Kuil Gigi di Kandy. Negara ini juga dikenal sebagai penghasil batu permata.',
      'qatar': 'Qatar adalah negara kecil di Jazirah Arab yang kaya akan cadangan gas alam dan minyak bumi. Ibukotanya adalah Doha, kota modern dengan gedung pencakar langit dan museum seni Islam. Qatar terkenal karena menjadi tuan rumah Piala Dunia FIFA 2022, yang pertama di Timur Tengah. Negara ini berinvestasi besar dalam infrastruktur dan pendidikan untuk mengurangi ketergantungan pada energi fosil.',
      'pakistan': 'Pakistan adalah negara di Asia Selatan yang berbatasan dengan India, Afghanistan, Iran, dan China. Ibukotanya adalah Islamabad, sedangkan kota terbesarnya adalah Karachi. Pakistan memiliki lanskap alam yang beragam, dari pegunungan Himalaya di utara hingga dataran Indus di selatan. Negara ini memiliki warisan sejarah peradaban Lembah Indus dan situs-situs arkeologi kuno. Islam adalah agama mayoritas dan menjadi dasar identitas nasional.',
      'irlandia': 'Irlandia adalah negara pulau di Eropa Barat yang dikenal dengan pemandangan hijau perbukitan, tebing dramatis, dan budaya Celtic. Ibukotanya adalah Dublin, kota yang terkenal dengan pub-pub khas dan sastra yang melahirkan penulis seperti James Joyce. Irlandia memiliki tradisi musik rakyat, festival St. Patrick, dan olahraga Gaelic. Negara ini juga dikenal dengan sebutan Emerald Isle karena lanskapnya yang hijau subur.',
      'filipina': 'Filipina adalah negara kepulauan di Asia Tenggara yang terdiri dari lebih dari 7.000 pulau. Ibukotanya adalah Manila, sedangkan pusat bisnisnya terletak di Metro Manila. Filipina dikenal dengan pantai tropisnya yang indah seperti Boracay, Palawan, dan Cebu. Negara ini memiliki warisan budaya campuran dari pengaruh Melayu, Spanyol, dan Amerika. Bahasa resmi adalah Filipina dan Inggris, dan mayoritas penduduknya beragama Katolik. Ekonomi Filipina berkembang di sektor jasa, BPO, dan remitansi dari pekerja migran.',
      'iran': 'Iran adalah negara di Asia Barat yang terkenal dengan sejarah Persia kuno. Ibukotanya adalah Teheran, kota metropolitan terbesar di negara tersebut. Iran memiliki warisan budaya yang kaya dengan situs bersejarah seperti Persepolis dan Masjid Shah di Isfahan. Negara ini memiliki cadangan minyak bumi dan gas alam yang besar. Budaya Iran terkenal dengan seni kaligrafi, puisi, musik tradisional, serta masakan khas seperti kebab dan saffron rice.',
      'perancis polinesia': 'Polinesia Prancis adalah wilayah seberang laut milik Prancis yang terletak di Samudra Pasifik. Wilayah ini terkenal dengan pulau-pulaunya yang indah seperti Tahiti dan Bora Bora, destinasi wisata mewah dengan laguna biru jernih dan resort eksklusif. Ibukotanya adalah Papeete di pulau Tahiti. Penduduknya memadukan budaya Polinesia dengan pengaruh Prancis. Pariwisata dan budidaya mutiara adalah sektor ekonomi utama Polinesia Prancis.',
      'maroko': 'Maroko adalah negara di Afrika Utara yang terletak di pesisir Samudra Atlantik dan Laut Mediterania. Ibukotanya adalah Rabat, sedangkan kota terbesar dan pusat bisnis adalah Casablanca. Maroko terkenal dengan kota-kota bersejarah seperti Marrakesh, Fes, dan Chefchaouen yang penuh warna. Budaya Maroko merupakan perpaduan Arab, Berber, dan pengaruh Eropa. Negara ini terkenal dengan pasar tradisional (souk), rempah-rempah, arsitektur mozaik, dan kuliner tajine.',
      'finlandia': 'Finlandia adalah negara di Eropa Utara yang dikenal dengan kualitas pendidikan terbaik di dunia, alam yang masih asri, dan fenomena alam Aurora Borealis. Ibukotanya adalah Helsinki. Finlandia terkenal sebagai salah satu negara paling bahagia di dunia dengan tingkat kesejahteraan tinggi. Negara ini memiliki ribuan danau dan hutan luas. Budaya Finlandia juga dikenal dengan sauna dan olahraga musim dingin. Finlandia merupakan negara kelahiran perusahaan teknologi seperti Nokia.',
      'argentina': 'Argentina adalah negara terbesar kedua di Amerika Selatan setelah Brasil, terkenal dengan dataran Pampas yang luas dan Pegunungan Andes di barat. Ibukotanya adalah Buenos Aires, kota kosmopolitan yang dikenal dengan arsitektur Eropa dan kehidupan malam yang semarak. Argentina terkenal sebagai negara asal tarian tango dan juga memiliki budaya sepak bola yang kuat dengan pemain legendaris seperti Diego Maradona dan Lionel Messi. Negara ini kaya akan sumber daya alam dan memiliki sektor pertanian yang maju, khususnya daging sapi dan produk kedelai.',
      'mexico': 'Meksiko adalah negara di Amerika Utara yang berbatasan langsung dengan Amerika Serikat di utara dan Guatemala serta Belize di selatan. Ibukotanya adalah Mexico City, salah satu kota metropolitan terbesar di dunia. Meksiko memiliki warisan peradaban kuno seperti Suku Aztec dan Maya yang meninggalkan banyak situs arkeologi terkenal seperti Chichen Itza dan Teotihuacan. Negara ini terkenal dengan kebudayaan penuh warna, musik mariachi, festival Día de los Muertos, serta kuliner khas seperti taco, burrito, dan guacamole. Ekonomi Meksiko berkembang pesat di sektor manufaktur, pertambangan, dan pariwisata.',
      'yunani': 'Yunani adalah negara di Eropa Tenggara yang dianggap sebagai tempat lahirnya peradaban Barat. Ibukotanya adalah Athena, kota bersejarah dengan peninggalan kuno seperti Acropolis dan Parthenon. Yunani terkenal dengan warisan filsafat, seni, demokrasi, dan mitologi Yunani yang mendunia. Negara ini memiliki ribuan pulau indah di Laut Aegea dan Laut Ionia, seperti Santorini dan Mykonos, yang menjadi tujuan wisata populer. Kuliner Yunani juga terkenal dengan bahan segar seperti zaitun, keju feta, dan gyros.',
      'portugal': 'Portugal adalah negara di Eropa Barat Daya yang terletak di Semenanjung Iberia bersama Spanyol. Ibukotanya adalah Lisbon, kota pesisir yang terkenal dengan jalanan berbatu, trem kuning, dan bangunan bersejarah. Portugal memiliki sejarah penjelajahan yang kuat pada abad ke-15 dan 16 dengan tokoh seperti Vasco da Gama dan Ferdinand Magellan. Negara ini terkenal dengan musik Fado, anggur Port, dan kawasan wisata Algarve dengan pantai indahnya.',
      'norwegia': 'Norwegia adalah negara di Eropa Utara yang terkenal dengan fjord-nya yang spektakuler, pegunungan, dan pemandangan alam Arktik. Ibukotanya adalah Oslo. Norwegia dikenal dengan standar hidup yang tinggi, sistem kesejahteraan sosial yang baik, serta sebagai salah satu negara paling bahagia di dunia. Negara ini kaya akan sumber daya alam seperti minyak bumi dan gas alam. Norwegia juga terkenal dengan Aurora Borealis atau cahaya utara yang menarik wisatawan setiap tahunnya.',
      'swedia': 'Swedia adalah negara Skandinavia di Eropa Utara yang terkenal dengan inovasi teknologi, desain minimalis, dan kesejahteraan sosialnya. Ibukotanya adalah Stockholm, kota yang dibangun di atas pulau-pulau yang indah. Swedia dikenal dengan merek-merek global seperti IKEA, Volvo, dan Spotify. Negara ini memiliki alam yang asri dengan hutan luas, danau, serta tradisi Midsummer yang meriah. Swedia juga berperan aktif dalam isu lingkungan dan perdamaian dunia.',
      'belanda': 'Belanda adalah negara di Eropa Barat yang terkenal dengan kincir angin, ladang tulip, kanal indah, dan budaya bersepeda. Ibukotanya adalah Amsterdam, kota dengan arsitektur bersejarah, museum seni, dan kehidupan malam yang semarak. Belanda memiliki sejarah panjang sebagai negara maritim dengan banyak koloni di masa lampau. Negara ini terkenal dengan sistem polder untuk mengendalikan air dan menjaga daratan tetap kering. Produk keju dan sepatu kayu klompen juga menjadi ciri khas budaya Belanda.',
      'chile': 'Chile adalah negara panjang di Amerika Selatan yang membentang dari gurun Atacama di utara hingga Patagonia di selatan. Ibukotanya adalah Santiago, pusat ekonomi dan budaya negara. Chile terkenal dengan pemandangan alamnya yang luar biasa, mulai dari pegunungan Andes, pulau Paskah (Easter Island), hingga kebun anggur di Lembah Casablanca. Negara ini memiliki ekonomi yang stabil dengan pertambangan tembaga sebagai sektor utama. Chile juga terkenal dengan kualitas anggur dan budaya musik folk tradisionalnya.',
      'new zealand': 'Selandia Baru adalah negara kepulauan di barat daya Samudra Pasifik yang terdiri dari dua pulau utama: Pulau Utara dan Pulau Selatan. Ibukotanya adalah Wellington, sedangkan kota terbesarnya adalah Auckland. Selandia Baru dikenal dengan keindahan alamnya seperti pegunungan Alpen Selatan, danau, dan hutan hujan. Negara ini terkenal sebagai lokasi syuting film The Lord of the Rings. Budaya Maori masih lestari di Selandia Baru dan menjadi bagian penting dari identitas nasional. Selain pariwisata, pertanian dan peternakan domba juga mendukung ekonomi negara ini.',
      'thailand': 'Thailand adalah negara di Asia Tenggara yang terkenal dengan julukan Negeri Gajah Putih. Ibukotanya adalah Bangkok, kota yang ramai dengan kuil Buddha megah, pasar terapung, dan kehidupan malam yang semarak. Thailand terkenal dengan keindahan pantai tropis seperti Phuket, Koh Samui, dan Krabi. Budaya Thailand sangat dipengaruhi agama Buddha dengan banyak festival keagamaan yang meriah. Kuliner Thailand mendunia dengan cita rasa khas seperti Tom Yum, Pad Thai, dan Mango Sticky Rice.',
      'swiss': 'Swiss adalah negara di Eropa Tengah yang terkenal dengan pegunungan Alpen, keindahan alam, serta stabilitas ekonomi dan politiknya. Ibukotanya adalah Bern, sedangkan kota-kota besar lainnya seperti Zurich dan Jenewa menjadi pusat keuangan internasional. Swiss dikenal dengan produk keuangannya seperti perbankan dan asuransi, serta industri jam tangan mewah. Negara ini juga terkenal dengan cokelat, keju, dan kualitas hidup yang tinggi. Swiss memiliki kebijakan netralitas yang sudah lama dan menjadi markas banyak organisasi internasional seperti Palang Merah.',
      'afrika selatan': 'Afrika Selatan adalah negara di ujung selatan benua Afrika yang dikenal dengan keanekaragaman budaya, bahasa, dan pemandangan alamnya. Negara ini memiliki tiga ibu kota: Pretoria (eksekutif), Cape Town (legislatif), dan Bloemfontein (yudikatif). Afrika Selatan terkenal dengan sejarah perjuangan anti-apartheid yang dipimpin Nelson Mandela. Negara ini memiliki keindahan alam luar biasa seperti Taman Nasional Kruger, Table Mountain, dan garis pantai yang mempesona. Ekonomi Afrika Selatan didukung sektor pertambangan, pariwisata, dan pertanian.',
      'saudi arabia': 'Arab Saudi adalah negara di Jazirah Arab yang dikenal sebagai pusat agama Islam karena menjadi lokasi dua kota suci, Mekkah dan Madinah. Ibukotanya adalah Riyadh. Arab Saudi merupakan salah satu produsen minyak bumi terbesar di dunia dan memiliki pengaruh besar di pasar energi global. Negara ini memiliki kebudayaan Islam yang kental dengan tradisi dan hukum syariah. Dalam beberapa tahun terakhir, Arab Saudi melakukan berbagai transformasi ekonomi dan sosial melalui program Visi 2030 untuk mengurangi ketergantungan pada minyak.',
      'korea selatan': 'Korea Selatan adalah negara di Asia Timur yang terletak di Semenanjung Korea, berbatasan langsung dengan Korea Utara. Ibukotanya adalah Seoul, kota modern dengan teknologi tinggi dan budaya pop yang mendunia. Korea Selatan dikenal dengan K-pop, drama Korea (K-Drama), dan industri hiburan yang mendunia. Negara ini juga memiliki industri teknologi maju dengan perusahaan raksasa seperti Samsung dan Hyundai. Selain itu, Korea Selatan memiliki destinasi wisata populer seperti Pulau Jeju, Istana Gyeongbokgung, dan Namsan Tower.',
      'spanyol': 'Spanyol adalah negara di Eropa Barat Daya yang terletak di Semenanjung Iberia bersama Portugal. Ibukotanya adalah Madrid, sedangkan kota-kota lainnya seperti Barcelona, Sevilla, dan Valencia juga terkenal secara global. Spanyol memiliki sejarah panjang sebagai kerajaan besar yang pernah menguasai banyak wilayah di dunia pada era penjelajahan. Budaya Spanyol terkenal dengan tarian flamenco, festival Tomatina, dan tradisi matador. Negara ini juga dikenal karena kuliner khasnya seperti paella, tapas, dan churros.',
      'mesir': 'Mesir adalah negara di Afrika Utara yang terkenal dengan peradaban Mesir Kuno dan peninggalannya seperti Piramida Giza, Sphinx, dan Sungai Nil. Ibukotanya adalah Kairo, kota metropolitan terbesar di dunia Arab. Mesir memiliki peranan penting dalam sejarah sebagai salah satu peradaban tertua di dunia. Negara ini juga menjadi pusat kebudayaan dan pendidikan di Timur Tengah. Selain warisan sejarahnya, Mesir modern juga memiliki ekonomi yang berkembang di sektor pariwisata, pertanian, dan energi.',
      'turki': 'Turki adalah negara transkontinental yang sebagian wilayahnya terletak di Asia dan sebagian lagi di Eropa. Ibukotanya adalah Ankara, sedangkan kota terbesarnya adalah Istanbul, kota bersejarah yang dahulu bernama Konstantinopel. Turki memiliki sejarah panjang sebagai pusat Kekaisaran Bizantium dan Kesultanan Ottoman. Negara ini kaya akan situs bersejarah seperti Hagia Sophia, Topkapi Palace, dan Pamukkale. Budaya Turki merupakan perpaduan pengaruh Timur dan Barat, terkenal dengan kuliner khas seperti kebab, baklava, dan teh Turki.',
      'brasil': 'Brasil adalah negara terbesar di Amerika Selatan dan negara berbahasa Portugis terbesar di dunia. Ibukotanya adalah Brasília, sedangkan kota terbesarnya adalah São Paulo. Brasil terkenal dengan hutan hujan Amazon yang menjadi paru-paru dunia serta keanekaragaman flora dan fauna tropisnya. Negara ini juga terkenal dengan sepak bola, Karnaval Rio de Janeiro, dan Pantai Copacabana. Brasil memiliki perekonomian terbesar di Amerika Latin dengan sektor pertanian, pertambangan, dan energi yang sangat berkembang. Budaya Brasil dikenal penuh warna dengan musik samba dan tarian capoeira.',
      'amerika': 'Amerika Serikat adalah sebuah negara federasi yang terletak di benua Amerika Utara, terdiri dari 50 negara bagian dengan ibu kota di Washington, D.C. Amerika Serikat dikenal sebagai salah satu negara adidaya di dunia dengan pengaruh besar dalam bidang ekonomi, politik, militer, teknologi, dan budaya. Negara ini memiliki populasi lebih dari 330 juta jiwa, menjadikannya negara dengan penduduk terbesar ketiga di dunia. Amerika Serikat terkenal dengan keberagamannya karena merupakan tempat bertemunya berbagai ras, etnis, dan budaya dari seluruh dunia. Negara ini juga memiliki banyak landmark terkenal seperti Patung Liberty, Gedung Putih, Grand Canyon, dan Hollywood. Dalam bidang pendidikan dan penelitian, Amerika menjadi rumah bagi banyak universitas terkemuka seperti Harvard, MIT, dan Stanford yang menarik mahasiswa internasional dari berbagai negara.',
      'inggris': 'Inggris adalah sebuah negara yang merupakan bagian dari Britania Raya (United Kingdom) bersama dengan Skotlandia, Wales, dan Irlandia Utara. Ibukota Inggris adalah London, yang juga menjadi pusat keuangan, budaya, dan pemerintahan. Inggris memiliki sejarah panjang yang berpengaruh besar terhadap perkembangan peradaban Barat, termasuk di bidang politik, sastra, ilmu pengetahuan, dan industri. Negara ini dikenal sebagai tempat lahirnya tokoh-tokoh penting seperti William Shakespeare, Isaac Newton, dan Charles Darwin. Bahasa Inggris yang berasal dari negara ini kini menjadi bahasa internasional yang digunakan di seluruh dunia. Selain itu, Inggris terkenal dengan klub-klub sepak bola populernya seperti Manchester United, Liverpool, dan Chelsea, serta berbagai destinasi wisata ikonik seperti Big Ben, Istana Buckingham, dan Stonehenge.',
      'prancis': 'Prancis adalah sebuah negara di Eropa Barat yang terkenal sebagai salah satu negara dengan pengaruh budaya, sejarah, dan seni yang sangat besar di dunia. Ibukotanya adalah Paris, kota yang sering dijuluki Kota Cahaya dan menjadi pusat mode, seni, kuliner, serta pariwisata dunia. Prancis memiliki sistem pemerintahan republik dan merupakan anggota pendiri Uni Eropa, NATO, serta PBB. Negara ini juga dikenal dengan bangunan bersejarahnya seperti Menara Eiffel, Istana Versailles, dan Katedral Notre-Dame. Prancis memiliki perekonomian yang kuat, menjadi salah satu negara dengan ekonomi terbesar di Eropa. Selain itu, Prancis terkenal dengan keanekaragaman kulinernya seperti keju, roti baguette, dan anggur yang mendunia. Bahasa Prancis juga merupakan salah satu bahasa resmi PBB dan digunakan di banyak negara di berbagai benua.',
      'jepang': 'Jepang adalah sebuah negara kepulauan di Asia Timur yang terkenal dengan kemajuan teknologi, budaya tradisional, dan pop culture seperti anime dan manga. Ibukotanya adalah Tokyo, salah satu kota terpadat dan pusat keuangan dunia. Jepang memiliki empat pulau utama: Honshu, Hokkaido, Kyushu, dan Shikoku. Negara ini terkenal dengan produk teknologi canggih, industri otomotif, serta kereta cepat Shinkansen. Jepang juga memiliki banyak destinasi wisata populer seperti Gunung Fuji, Kyoto dengan kuil-kuilnya, dan Hokkaido yang terkenal dengan musim dinginnya. Jepang dikenal akan kedisiplinan masyarakatnya, makanan khas seperti sushi dan ramen, serta festival budaya yang unik.',
      'australia': 'Australia adalah negara sekaligus benua yang terletak di belahan selatan bumi. Negara ini terkenal dengan keindahan alamnya yang unik, seperti Great Barrier Reef, Uluru, dan pantai-pantai indahnya. Ibukotanya adalah Canberra, sementara kota terbesar adalah Sydney yang terkenal dengan Opera House dan Harbour Bridge. Australia memiliki sistem pemerintahan monarki konstitusional dengan Ratu Inggris sebagai kepala negara. Negara ini kaya akan flora dan fauna khas seperti kanguru dan koala. Selain itu, Australia juga menjadi tujuan studi populer bagi mahasiswa internasional karena kualitas pendidikannya yang tinggi dan lingkungan yang multikultural.',
      'indonesia': 'Indonesia adalah negara kepulauan terbesar di dunia dengan lebih dari 17.000 pulau, terletak di kawasan Asia Tenggara yang diapit oleh Samudra Pasifik dan Samudra Hindia. Indonesia memiliki populasi lebih dari 270 juta jiwa, menjadikannya negara berpenduduk terbesar keempat di dunia setelah Tiongkok, India, dan Amerika Serikat. Ibu kotanya adalah Jakarta, kota metropolitan yang juga termasuk salah satu kota terpadat di dunia. Indonesia dikenal dengan keanekaragaman budaya, suku bangsa, bahasa daerah, serta kekayaan alamnya yang melimpah seperti hutan hujan tropis, tambang mineral, dan hasil laut. Indonesia juga merupakan negara dengan penduduk Muslim terbanyak di dunia dan tergabung dalam berbagai organisasi internasional seperti ASEAN, G20, dan PBB. Selain itu, Indonesia terkenal dengan destinasi wisata alamnya seperti Bali, Raja Ampat, Lombok, dan Taman Nasional Komodo yang mendunia.',
      'udah makan apa': 'Tadi makan mie sama telur, enak banget deh sampe nambah.',
      'china': 'China atau Tiongkok adalah negara terluas ketiga di dunia yang terletak di Asia Timur, dengan jumlah penduduk terbesar di dunia, melebihi 1,4 miliar jiwa. Ibukotanya adalah Beijing, sedangkan kota terbesar sekaligus pusat keuangan adalah Shanghai. China memiliki sejarah peradaban ribuan tahun yang melahirkan berbagai penemuan penting seperti kertas, bubuk mesiu, dan kompas. Negara ini terkenal dengan keajaiban arsitekturnya seperti Tembok Besar China dan Kota Terlarang. Dalam beberapa dekade terakhir, China tumbuh menjadi kekuatan ekonomi dan teknologi global dengan sektor manufaktur yang mendominasi pasar dunia.',
      'kanada': 'Kanada adalah negara terluas kedua di dunia setelah Rusia, terletak di Amerika Utara dan berbatasan langsung dengan Amerika Serikat. Ibukotanya adalah Ottawa, sedangkan kota-kota besar lainnya adalah Toronto, Vancouver, dan Montreal. Kanada dikenal dengan keindahan alamnya yang luar biasa seperti Danau Louise, Pegunungan Rocky, dan Taman Nasional Banff. Negara ini memiliki sistem pemerintahan monarki konstitusional dengan Ratu Inggris sebagai kepala negara. Kanada terkenal sebagai negara multikultural dengan penduduk yang ramah dan kualitas hidup yang tinggi. Negara ini juga terkenal dalam bidang olahraga musim dingin seperti hoki es.',
      'lagi mikirin apa': 'Lagi mikirin mau liburan kemana kalo ada cuti panjang.',
      'kangen banget sama kamu': 'Aku juga kangen banget, rasanya pengen ketemu tiap hari.',
      'besok kerja kan': 'Iya besok masuk kerja lagi, semoga lancar semua urusannya.',
      'kok ga mau': 'Bukan ga mau, cuma lagi pengen sendiri dulu bentar.',
      'kenapa diem aja': 'Diem aja karena lagi ga tau mau ngomong apa sebenernya.',
      'pura pura ga tau': 'Engga pura pura, aku emang beneran ga tau kok.',
      'kok bohong': 'Serius deh, aku ga bohong sama sekali kok.',
      'bohong terus': 'Yaudah deh maaf kalo kedengeran kayak bohong.',
      'jangan bohong': 'Iya janji ga bohong lagi deh, maaf banget ya.',
      'udah maafin belum': 'Udah kok, ga usah dibahas lagi ya biar ga makin panjang.',
      'pura pura lupa': 'Haha engga pura pura, cuma beneran lupa aja kok.',
      'ga percaya kamu': 'Percaya deh, aku ga pernah mainin kamu kok.',
      'lagi capek banget': 'Capek banget hari ini, pengen rebahan seharian kalo bisa.',
      'besok temenin': 'Boleh banget, kabarin aja jam berapa mau berangkat.',
      'temenin belanja': 'Oke siap, belanja apa aja nih kira-kira?',
      'mau kado apa': 'Aku ga minta apa-apa, yang penting kamu sehat aja udah cukup.',
      'udah mandi sore': 'Udah kok, tadi mandi sekalian nyuci baju juga.',
      'belum mandi sore': 'Belum mandi, rencananya nanti abis maghrib mandi deh.',
      'mau ketemu': 'Mau banget ketemu, udah kangen ngobrol langsung.',
      'kok telat banget': 'Telat karena tadi nunggu jemputan agak lama dikit.',
      'kapan pulang kerja': 'Pulang kerja jam 5 sore biasanya, kalo ga lembur.',
      'kapan libur kerja': 'Libur kerja kalo weekend aja, kadang suka lembur juga.',
      'lagi di kantor': 'Iya lagi di kantor ngerjain laporan sama deadline.',
      'udah di rumah belum': 'Udah di rumah kok, baru nyampe tadi abis maghrib.',
      'lagi ngerjain apa': 'Lagi ngerjain tugas kantor yang deadline-nya mepet banget.',
      'udah makan bareng': 'Udah makan bareng keluarga tadi, seru banget rame-rame.',
      'kok ga ngajak': 'Hehe maaf ya, nanti kalo ada lagi aku ajak deh.',
      'besok kemana': 'Besok rencananya mau ke mall bentar beli keperluan.',
      'mau ikut': 'Mau banget sih, tapi kamu beneran bisa ga nih?',
      'ayo berangkat bareng': 'Oke gas bareng, biar rame juga kan seru.',
      'udah tidur nyenyak': 'Belum nyenyak, tidurnya kebangun-bangun terus.',
      'besok bangunin ya': 'Oke siap, besok aku bangunin pake chat manis ya.',
      'kok ghosting': 'Haha engga ghosting kok, cuma lagi bener-bener sibuk aja.',
      'lagi main game': 'Iya lagi main game bentar biar ga bosen.',
      'main game apa': 'Main game mobile yang biasa kita main bareng itu loh.',
      'kapan main bareng': 'Kapanpun kamu mau, aku siap nemenin main bareng.',
      'jangan tinggalin': 'Ga bakal aku tinggalin, tenang aja ya.',
      'lagi ngopi': 'Iya lagi ngopi santai sambil balas chat kamu.',
      'kopi apa': 'Kopi hitam pake sedikit gula biar ga terlalu pahit.',
      'mau bikin kopi': 'Mau bikin kopi juga? Bikinin aku juga dong hehe.',
      'jangan galak': 'Hehe maaf ya kalo keliatannya galak, padahal engga kok.',
      'kamu lucu': 'Makasih ya, kamu juga lucu banget sampe bikin senyum sendiri.',
      'ga lucu ah': 'Lucu kok, malah bikin gemes tiap ngobrol gini.',
      'mau jalan': 'Mau banget jalan, kapan nih kita atur waktunya?',
      'mau ketemu ga': 'Mau banget dong, kapan pun aku sempetin kok.',
      'kapan ada waktu': 'Minggu depan kayaknya bisa deh, semoga ga ada halangan.',
      'lagi di jalan': 'Iya lagi di jalan pulang nih, doain lancar ya.',
      'udah makan di luar': 'Udah makan di luar bareng temen, lumayan ngobrol-ngobrol juga.',
      'jangan marah': 'Iya kok ga marah, aku ngerti kok tenang aja.',
      'udah ga marah': 'Udah ga marah sama sekali kok, makasih udah sabar ya.',
      'lagi benerin apa': 'Lagi benerin laptop yang error terus, bikin kesel aja.',
      'kok ribet': 'Hehe emang ribet tapi harus diselesain biar lega.',
      'kapan selesai': 'Mungkin besok kelar semua kalo ga ada kendala lagi.',
      'udah siapin semua': 'Udah siapin semua keperluan, tinggal jalan aja besok.',
      'besok jam berapa': 'Jam 9 pagi kayaknya udah siap semua deh.',
      'bangunin pagi ya': 'Oke, besok aku bangunin pagi biar ga telat.',
      'kok masih online': 'Masih online soalnya belum ngantuk sama sekali.',
      'kok off': 'Off bentar tadi, sekarang udah online lagi kok.',
      'udah maem': 'Udah makan kenyang banget sampe ngantuk hehe.',
      'lagi nyari apa': 'Lagi nyari ide buat kerjaan besok biar ga keteteran.',
      'udah beres': 'Udah beres semua, sekarang tinggal santai-santai aja.',
      'kapan pulang lagi': 'Mungkin pulang minggu depan kalo ga ada halangan.',
      'kok males': 'Males banget keluar rumah soalnya cuaca panas banget.',
      'lagi mager': 'Iya mager banget hari ini, pengen rebahan aja seharian.',
      'besok mau kemana': 'Besok mau belanja bulanan sama jalan-jalan dikit.',
      'udah mandi pagi': 'Udah mandi pagi, seger banget rasanya.',
      'belum mandi pagi': 'Belum mandi, masih malas gerak dari kasur.',
      'udah nyuci baju': 'Udah nyuci baju, sekarang tinggal jemur doang.',
      'lagi masak apa': 'Lagi masak mie instan doang, simple tapi enak.',
      'udah makan di warung': 'Udah makan di warung langganan, murah dan enak.',
      'lagi di warung': 'Iya lagi di warung sambil makan sama temen.',
      'kapan traktir': 'Traktir kapan aja kalo ada rezeki lebih hehe.',
      'lagi ngerjain tugas': 'Iya lagi ngerjain tugas deadline, pusing juga nih.',
      'tugas apa': 'Tugas kantor yang numpuk banget akhir bulan.',
      'udah selesai tugas': 'Udah selesai tugasnya, sekarang mau istirahat bentar.',
      'kok begadang': 'Begadang gara-gara kerjaan belum kelar semua.',
      'kok susah tidur': 'Susah tidur soalnya banyak pikiran banget.',
      'besok pagi sibuk': 'Besok pagi lumayan sibuk, tapi masih bisa chat kok.',
      'kok jarang ketemu': 'Iya jarang ketemu soalnya sama-sama sibuk banget.',
      'mau diceritain': 'Mau diceritain apa nih? Aku dengerin kok.',
      'cerita apa': 'Cerita apa aja deh yang bikin kamu seneng.',
      'kapan ke sana': 'Mungkin minggu depan aku sempetin ke sana deh.',
      'jangan jauh jauh': 'Iya kok ga bakal jauh-jauh dari kamu.',
      'kapan pulang telat': 'Pulang telat kalo kerjaan numpuk banget, sabar ya.',
      'kok susah dihubungi': 'Susah dihubungi soalnya HP aku sering mati baterai.',
      'mau ketemu diem diem': 'Hehe boleh banget, diem diem aja biar seru.',
      'kok mendadak': 'Mendadak soalnya ga kepikiran mau bilang duluan.',
      'udah di parkiran': 'Udah di parkiran nih, tinggal nunggu kamu aja.',
      'lagi tunggu siapa': 'Lagi tunggu kamu keluar aja kok.',
      'kok lama banget': 'Maaf ya, tadi macet parah di jalan.',
      'kangen ngobrol': 'Aku juga kangen ngobrol panjang lebar sama kamu.',
      'kok rindu': 'Rindu banget, rasanya udah lama ga ketemu kamu.',
      'kapan bisa bareng': 'Kapan aja bisa bareng, asalkan waktunya pas.',
      'jangan lupa janji': 'Iya janji ga akan aku lupain kok.',
      'udah pegel': 'Pegel banget duduk terus dari pagi tadi.',
      'lagi bengong': 'Iya lagi bengong sambil mikirin kamu.',
      'kok nyuekin': 'Hehe engga nyuekin kok, cuma lagi ga banyak kata.',
      'lagi download apa': 'Lagi download file kerjaan buat besok pagi.',
      'lagi upload apa': 'Lagi upload tugas kantor ke server online.',
      'kok ketawa': 'Ketawa gara-gara chat kamu lucu banget sumpah.',
      'lagi nyanyi apa': 'Lagi nyanyi lagu yang kamu suka banget itu loh.',
      'kok nyanyi': 'Nyanyi biar ga bosan aja di rumah sendirian.',
      'halo': 'Halo juga! 👋',
      'test': 'Test berhasil!',
      'menu': 'Ini menu botnya 📝',
      'ping': 'Pong!',
      'hai': 'Hai juga!',
      'help': 'Ini bantuan: Ketik kata kunci yg tersedia.',
      'info': 'Ini info singkat bot ini.',
      'thanks': 'Sama-sama! 😊',
      'oke': 'Oke, sip!',
      'bye': 'Sampai jumpa! 👋',
      'assalamualaikum': 'waalaikumsalam',
      'pinjam duit mar': 'lagi gak ada duit aku',
      'bangsat': 'kau lebih bangsat',
      'apaan tu': 'gapapa, lagi iseng',
      'oowhh': 'ya oowhh',
      'Mar di kede ada gas agak cantik gk': 'kurang tau, nanti ku kabarin',
      'mar': 'saya',
      'jelek': 'Emang jelek',
      'topup': 'https://www.sipshop.co.id/id-id/mobile-legends',
      'Bokep': 'https://164.92.247.92/moviestag/bokep-hijab/',
      'siap': 'oke gas',
      'iya bg': 'oke',
      'Mna kw': 'Rumah',
      'blom': 'Okelah kalau belum',
      'ok': 'ok',
      'Mar kpn gas msk': 'belum tahu',
      'sayang': 'tumben manggil sayang',
      'bang': 'ya',
      'p': 'ya',
      'pinjam': 'lagi gak bisa',
      'pulang': 'nanti',
      'nanti': 'kok nanti',
      'hai': 'hai juga',
      'halo': 'halo halo',
      'kamu siapa': 'aku bot kamu',
      'lagi apa': 'lagi rebahan',
      'sudah makan': 'belum nih',
      'sarapan belum': 'udah dong',
      'tidur dimana': 'di kasur lah',
      'udah mandi': 'belum, mager',
      'lagi dimana': 'di rumah',
      'kapan ketemu': 'kapan aja',
      'kangen aku': 'iya kangen',
      'sayang aku gak': 'sayang banget',
      'besok ngapain': 'belum tau',
      'mau kemana': 'kemana aja',
      'lagi sibuk ya': 'enggak kok',
      'kok slow respon': 'maaf ya',
      'bales dong': 'ini udah dibales',
      'lagi marah ya': 'enggak kok',
      'kok cuek': 'maaf ya',
      'kok gitu': 'gimana dong',
      'sibuk ya': 'lumayan',
      'udah makan siang': 'belum',
      'nanti jalan yuk': 'boleh banget',
      'pinjam duit': 'lagi gak ada',
      'minta pulsa': 'gak bisa',
      'transfer dulu': 'duh gak ada saldo',
      'bangun dong': 'udah bangun',
      'mau tidur': 'selamat tidur',
      'selamat pagi': 'pagi juga',
      'selamat malam': 'malam juga',
      'gimana kabar': 'baik banget',
      'apa kabar': 'baik, kamu?',
      'udah makan malam': 'belum nih',
      'lagi chat siapa': 'cuma kamu kok',
      'males banget': 'sama, males juga',
      'bete': 'kenapa bete?',
      'bosen': 'yuk ngobrol',
      'lagi galau': 'kenapa galau?',
      'kamu dimana': 'Aku lagi di rumah santai sambil ngopi, kamu sendiri lagi apa?',
      'makan apa': 'Aku barusan makan nasi goreng sama telur, kenyang banget hehe.',
      'ngapain aja': 'Seharian cuma rebahan sambil scroll HP, bosen juga sih sebenernya.',
      'udah makan belum': 'Udah kok, tadi makan bareng keluarga di dapur, rame banget.',
      'lagi sibuk apa': 'Lagi ngurus kerjaan dikit sama balas chat, kamu sendiri sibuk nggak?',
      'kok ga bales': 'Maaf banget ya, tadi lagi ketiduran bentar jadi ga liat chat masuk.',
      'kapan ketemu lagi': 'Mungkin weekend ini kita bisa ketemu, kalau kamu ada waktu ya.',
      'kenapa cuek': 'Aku nggak cuek kok, cuma lagi banyak pikiran aja akhir-akhir ini.',
      'kok tiba tiba hilang': 'Maaf banget, aku tadi tiba-tiba ada urusan mendadak jadi offline.',
      'lagi sama siapa': 'Aku cuma sendiri kok di kamar sambil dengerin musik santai.',
      'mau main ga': 'Mau banget sih, tapi kita atur waktu bareng ya biar pas dua-duanya.',
      'lagi bete ya': 'Iya nih, lagi bete dikit gara-gara cuaca panas banget seharian.',
      'besok libur ga': 'Besok libur kok, jadi aku bisa rebahan seharian sama main HP.',
      'kenapa diem': 'Aku diem soalnya lagi fokus ngerjain sesuatu, makanya slow respon.',
      'kok galak': 'Haha maaf, aku nggak galak kok, cuma nadanya emang gitu dari sananya.',
      'kapan pulang': 'Pulangnya masih lama kayaknya, soalnya masih ada yang mau diurus.',
      'kok pergi': 'Pergi sebentar doang kok, nanti juga balik lagi ke sini.',
      'udah tidur': 'Belum tidur nih, malah lagi scroll chat kamu sampe ketawa sendiri.',
      'belum tidur ya': 'Belum, lagi insomnia gara-gara kopi kebanyakan sore tadi.',
      'bangun belum': 'Baru aja bangun, padahal niatnya mau tidur siang bentar doang.',
      'lagi sibuk banget': 'Iya, lagi sibuk banget sama kerjaan yang numpuk dari kemarin.',
      'kok marah': 'Enggak marah kok, cuma nadanya aja yang bikin keliatan gitu.',
      'udah sarapan': 'Udah sarapan roti sama teh manis tadi pagi, lumayan bikin kenyang.',
      'kok ga jawab': 'Lagi mikir jawaban yang pas biar kamu seneng bacanya, hehe.',
      'udah siap': 'Udah siap lah, tinggal nunggu kamu aja yang belum siap jalan.',
      'lagi mikir': 'Lagi mikir mau makan apa nanti malem, bingung banget deh.',
      'lagi chat siapa': 'Chat sama temen-temen aja, kamu tetep nomor satu kok tenang aja.',
      'kangen banget': 'Aku juga kangen banget sama kamu, rasanya mau ketemu tiap hari.',
      'kok cepet banget': 'Cepet banget apa nih? Aku malah ngerasa waktu jalan lambat.',
      'beneran ya': 'Beneran lah, masa aku bohong sama kamu sih kan ga mungkin.',
      'yaudah deh': 'Yaudah deh kalau kamu maunya gitu, aku ikut aja kok.',
      'gapapa kok': 'Iya gapapa kok, aku nggak masalah sama sekali, santai aja.',
      'makasih ya': 'Makasih juga udah mau repot-repot chat aku duluan.',
      'pagi sayang': 'Pagi juga sayang, semoga harimu menyenangkan ya hari ini.',
      'malam sayang': 'Malam juga sayang, semoga mimpi indah nanti tidurnya.',
      'mimpi apa': 'Tadi mimpi jalan-jalan sama kamu ke pantai, seru banget rasanya.',
      'kok serem': 'Hahaha serem dari mana coba? Aku malah ngerasa lucu.',
      'serius amat': 'Iya serius lah, masa aku main-main sama kamu.',
      'males banget': 'Aku juga males banget sebenernya, tapi harus tetap dijalanin.',
      'kenapa kamu': 'Aku kenapa ya? Mungkin lagi pengen sendiri dulu kali ya.',
      'apa mau kamu': 'Aku cuma mau kamu seneng terus dan ga sedih lagi.',
      'udah sampe': 'Udah sampe nih, lagi nunggu kamu keluar juga.',
      'tunggu ya': 'Iya aku tunggu kok, santai aja ga buru-buru.',
      'ayo berangkat': 'Yuk gas lah, udah ga sabar mau jalan bareng kamu.',
      'lagi hujan': 'Iya nih lagi hujan deras banget di sini, dingin banget jadinya.',
      'lagi panas': 'Panas banget sampe males gerak dari kasur rasanya.',
      'dingin banget': 'Dingin banget sampe harus pake selimut tebel nih.',
      'kok nyebelin': 'Hehe maaf ya kalo aku nyebelin, padahal maksudnya bercanda.',
      'kapan nyusul': 'Nyusul bentar lagi kok, sabar ya tunggu aku.',
      'males jawab': 'Lagi males jawab panjang lebar, jadi jawabnya pendek aja ya.',
      'udah mandi belum': 'Belum mandi, lagi nunggu air anget dulu nih.',
      'belum mandi ya': 'Belum mandi, soalnya dingin banget males banget keluar kamar.',
      'nanti main yuk': 'Boleh banget, kabarin aja kapan dan dimana mau ketemuan.',
      'gausah lah': 'Yaudah deh kalo kamu ga mau, aku nurut aja.',
      'jangan gitu': 'Yaudah maaf deh kalo bikin kamu ga nyaman.',
      'kapan chat lagi': 'Chat lagi nanti malem ya, sekarang aku mau kerja dulu.',
      'udah ngantuk': 'Udah ngantuk banget tapi masih pengen ngobrol sama kamu.',
      'kok ketiduran': 'Ketiduran sambil nunggu balasan kamu nih, maaf ya.',
      'lagi nonton': 'Lagi nonton film drama sambil ngemil juga nih.',
      'nonton apa': 'Nonton film lama yang udah pernah ditonton, nostalgia aja.',
      'lagi dengerin': 'Lagi dengerin lagu galau sambil mikirin kamu.',
      'lagu apa': 'Lagu kesukaan kamu yang sering kamu setel di status tuh.',
      'pulang jam berapa': 'Kayaknya pulang jam 8 malem deh kalo ga macet.',
      'kok lama banget': 'Lama banget soalnya tadi jalanan macet parah.',
      'udah nyampe rumah': 'Udah nyampe rumah, sekarang mau makan dulu bentar.',
      'udah makan dirumah': 'Udah makan sama keluarga, seru banget rame-rame.',
      'ngajak makan': 'Mau ngajak makan tapi takut kamu lagi sibuk.',
      'jangan tidur dulu': 'Jangan tidur dulu dong, temenin aku ngobrol dulu.',
      'temenin dong': 'Iya aku temenin kok, mau ngobrolin apa nih sekarang?',
      'kapan pulang kampung': 'Mungkin bulan depan bisa pulang kampung bentar.',
      'kapan ketemuan lagi': 'Kapanpun kamu mau, aku usahain sempetin waktu kok.',
      'kok putus': 'Putus gimana maksudnya? Kita baik-baik aja kan?',
      'balikan yuk': 'Mau banget balikan, tapi kita harus saling jaga perasaan ya.',
      'lagi jalan sama siapa': 'Lagi jalan sendiri sambil muter-muter kota aja.',
      'temen siapa': 'Temen SMA yang udah lama ga ketemu, kangen juga.',
      'keluarga sehat': 'Alhamdulillah keluarga sehat semua, kamu gimana kabarnya?',
      'kangen rumah': 'Iya nih kangen rumah sama suasana kampung halaman.',
      'pengen liburan': 'Pengen banget liburan tapi cuti belum bisa diambil.',
      'kapan nikah': 'Haha sabar dulu dong, tunggu mapan dulu ya.',
      'serius banget': 'Iya serius banget, ga main-main kalo udah ngomongin ini.',
      'ga percaya': 'Yaudah deh kalo ga percaya, buktinya nanti aja.',
      'udah disini': 'Udah di tempat, tinggal nunggu kamu dateng.',
      'dimana nih': 'Aku di depan pintu masuk nih, coba cari aku.',
      'buru buru': 'Iya buru-buru biar ga telat sampe tujuan.',
      'kenapa lama': 'Lama soalnya tadi macet plus hujan deres banget.',
      'jalan hati hati': 'Iya aku hati-hati kok, kamu juga ya di rumah.',
      'udah sampe mana': 'Udah sampe setengah jalan, bentar lagi nyampe kok.',
      'ngantuk berat': 'Ngantuk berat banget tapi harus ditahan dulu nih.',
      'kok jarang chat': 'Maaf ya jarang chat, lagi banyak urusan aja.',
      'lagi sibuk kerja': 'Iya sibuk kerjaan numpuk banget akhir-akhir ini.',
      'semangat ya': 'Makasih udah nyemangatin, kamu juga ya semangat terus.',
      'jangan lupa makan': 'Iya jangan lupa makan juga, jangan sampe sakit.',
      'jaga kesehatan': 'Iya kamu juga jaga kesehatan ya, jangan kecapean.',
      'kok hilang': 'Hilang sebentar doang kok, sekarang udah balik lagi.',
      'kamu baik banget': 'Makasih ya udah bilang gitu, kamu juga baik kok.',
      'teman baik': 'Iya kamu temen baik banget buat aku, makasih ya.',
      'kok gitu sih': 'Gimana ya, aku juga bingung jelasinnya gimana.',
      'bilang dong': 'Yaudah aku bilang deh, aku kangen sama kamu.',
      'kangen beneran': 'Iya beneran kangen, ga bohong ini serius banget.',
      'apa bener': 'Bener kok, percaya deh sama aku ya.',
      'mau apa lagi': 'Aku ga mau apa-apa, cuma mau liat kamu seneng.',
      'udah deh': 'Udah deh gitu aja, jangan dibahas lagi ya.',
      'maaf ya': 'Gapapa kok, aku udah maafin dari tadi.',
      'mau minta maaf': 'Gausah minta maaf terus, aku ga marah kok.',
      'udah tidur kan': 'Belum tidur, lagi nunggu kamu bales chat nih.',
      'belum tidur juga': 'Iya belum, malah makin melek gara-gara ngobrol sama kamu.',
      'ga bisa tidur': 'Ga bisa tidur kalo belum denger suara kamu dulu.',
      'telpon yuk': 'Mau banget telpon, tapi kamu duluan yang telpon ya.',
      'video call yuk': 'Boleh banget video call, biar kangen terobati dikit.',
      'pamit tidur': 'Yaudah tidur dulu sana, mimpi indah ya.',
      'selamat istirahat': 'Selamat istirahat juga, semoga tidurnya nyenyak.',
      'mimpi indah': 'Semoga mimpi indah tentang hal-hal yang bikin bahagia.',

    };

    if (text && text.toLowerCase() in replies) {
      await sock.sendMessage(from, { text: replies[text.toLowerCase()] });
    }
    // Pesan lain diabaikan otomatis
  });
}

startBot();
